// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:90f22c13-3cd0-41ab-afde-1c9f53d9f2ef",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_2421GlOZW",
    "aws_user_pools_web_client_id": "4i0up41j5ub587fk6fjm0vttcr",
    "oauth": {}
};


export default awsmobile;
