// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    identityPoolId: 'ap-southeast-1:4e89e5bf-bc63-4b89-9dff-c667253a43b8',
	region: 'ap-southeast-1',
	userPoolId: 'ap-southeast-1_lB7j8AQm1',
	userPoolWebClientId: '7dnfdgtv2k6h9pbu210g8hjbht'
};


export default awsmobile;
